### ISSUE TITLE
Process fails when accepting licence

### ISSUE THREAD

**Issue by rickwalking** [hrueger/setup-nativescript#7]
There's an error happening when trying to run hrueger/setup-nativescript@v1.1.0

```
Run hrueger/setup-nativescript@v1.1.0
  with:
    nativescript-version: 7.0.10
Executing command "npm config set unsafe-perm=true"
/opt/hostedtoolcache/node/12.20.0/x64/bin/npm config set unsafe-perm=true
Process finished.
Executing command "mkdir -p /opt/android/sdk"
/usr/bin/mkdir -p /opt/android/sdk
Process finished.
Executing command "curl --silent --show-error --location --fail --retry 3 --output /t***/sdk-tools-linux-4333796.zip dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
/usr/bin/curl --silent --show-error --location --fail --retry 3 --output /t***/sdk-tools-linux-4333796.zip dl.google.com/android/repository/sdk-tools-linux-4333796.zip
Process finished.
Executing command "unzip -q /t***/sdk-tools-linux-4333796.zip -d /opt/android/sdk"
/usr/bin/unzip -q /t***/sdk-tools-linux-4333796.zip -d /opt/android/sdk
Process finished.
Executing command "rm /t***/sdk-tools-linux-4333796.zip"
/usr/bin/rm /t***/sdk-tools-linux-4333796.zip
Process finished.
Executing command "/bin/bash -c "yes | sdkmanager --licenses""
/bin/bash -c yes | sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Error: Error: The process '/bin/bash' failed with exit code 1
```

**Comment by hrueger** [comment]
Thanks for reporting this, I'll take a look at it in a few days.

**Comment by rickwalking** [comment]
Hey @hrueger Maybe there's something to do with the sdk installation process? Because it looks like it is trying to find a javax class and it is missing.

**Comment by hrueger** [comment]
@rickwalking Strange, I can't reproduce this issue. Please provide more information:
- What linux version do you run the action on?
- Are you using a custom runner?
- Could you maybe share your workflows `.yml` file?

**Comment by rickwalking** [comment]
@hrueger Thanks for the response!

- I'm using Ubuntu Latest
- No custom runner

My .yml file:
```
  build_app:
    needs: init
    name: Build App on Node.js ${{ matrix.node-version }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        node-version: [12]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Prepare ( checkout code and setup build environment )
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install deps and auth in private npm registry
      - name: Install npm-ci-login and angular-cli
        run: |
          yarn global add npm-ci-login @angular/cli@8.3.24
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: authenticate in proplugins.org
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 1
          max_attempts: 5
          command: npm-ci-login
        env:
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: "https://npm.proplugins.org"
          NPM_SCOPE: "@proplugins"

      - name: Write prod google-services.json
        if: needs.init.outputs.phase == 'prod'
        id: write_google_services_json
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "google-services.json"
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Move google-services.json from previous step to final destination
        if: needs.init.outputs.phase == 'prod'
        run: |
          mv ${{ steps.write_google_services_json.outputs.filePath }} /home/runner/work/front/front/native/App_Resources/Android/google-services.json
          cat /home/runner/work/front/front/native/App_Resources/Android/google-services.json

      - uses: hrueger/setup-nativescript@v1.1.0
        with:
          nativescript-version: "7.0.10"
```

**Comment by hrueger** [comment]
I created a test repo and ran your workflow but it completes without any errors: https://github.com/hrueger/tests/actions/runs/410446309
I also ran it again to make sure it's not a problem with caching: https://github.com/hrueger/tests/actions/runs/410450888 but it also completes successfully.
This is strange...
Can you still reproduce this error? Maybe it was just a temporary bug with the environment? This has happened to me multiple times, for example a Google server was not available once

**Comment by Cayan** [comment]
I just had the same issue

`
Run hrueger/setup-nativescript@v1.1.0
Executing command "npm config set unsafe-perm=true"
/opt/hostedtoolcache/node/12.20.0/x64/bin/npm config set unsafe-perm=true
Process finished.
Executing command "mkdir -p /opt/android/sdk"
/usr/bin/mkdir -p /opt/android/sdk
Process finished.
Executing command "curl --silent --show-error --location --fail --retry 3 --output /t***/sdk-tools-linux-4333796.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
/usr/bin/curl --silent --show-error --location --fail --retry 3 --output /t***/sdk-tools-linux-4333796.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
Process finished.
Executing command "unzip -q /t***/sdk-tools-linux-4333796.zip -d /opt/android/sdk"
/usr/bin/unzip -q /t***/sdk-tools-linux-4333796.zip -d /opt/android/sdk
Process finished.
Executing command "rm /t***/sdk-tools-linux-4333796.zip"
/usr/bin/rm /t***/sdk-tools-linux-4333796.zip
Process finished.
Executing command "/bin/bash -c "yes | sdkmanager --licenses""
/bin/bash -c yes | sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Error: Error: The process '/bin/bash' failed with exit code 1
`

**Comment by hrueger** [comment]
@Cayan Interesting. Could you please provide more information?
See above:
> - What linux version do you run the action on?
> - Are you using a custom runner?
> - Could you maybe share your workflows `.yml` file?

**Comment by jnorkus** [comment]
I started getting this same issue yesterday without changing anything in my workflow. The reason seems to be incompatibility between `sdkmanager` and `adoptopenjdk-11`.

**Comment by hrueger** [comment]
Ah, thanks for the hint. I'll look into that in a couple of days.

**Comment by hrueger** [comment]
Sorry for the delay, could you please try the just released `v1.2.0`?

**Comment by hrueger** [comment]
Let's close this due to it being almost 4 years old ;-) Feel free to create a new issue in case you encounter the same problem again.
